/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.Collections;

/**
 *
 * @author drakm
 */
public class AnsvarigTaBort extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnsvarigTaBort.class.getName());
    private InfDB idb;
    private String currentPid;
    private String currentRad;

    /**
     * Creates new form AnsvarigTaBort
     */
    public AnsvarigTaBort(InfDB idb, String currentPid, String currentRad) {
        this.idb = idb;
        this.currentPid = currentPid;
        this.currentRad = currentRad;
        initComponents();
        setTitle();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxData = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboxData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(this::btnTaBortActionPerformed);

        lblTitle.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cboxData, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnTaBort)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaBort))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //När man klickar på "Ta bort"-knappen så tas partnern eller handläggaren bort
    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        String sqlQ = "";
        String id = "";
        
        //Användaren får en pop-up om de värkligen vill ta bort informationen
        if(JOptionPane.showConfirmDialog(this, "Är du säker på att du vill ta bort denna data", "Ta bort data?", WIDTH) == 0)
        {
            //Om användaren valde att ta bort en partner
            if(currentRad == "Partner")
            {
                id = cboxData.getSelectedItem().toString();
                id = id.substring(0, id.indexOf('.'));
                sqlQ = "delete from projekt_partner where pid = " + currentPid + " and partner_pid = " + id;
            }
            //Om användaren valde att ta bort en handläggare
            else if(currentRad == "Handläggare")
            {
                id = cboxData.getSelectedItem().toString();
                id = id.substring(0, id.indexOf('.'));
                sqlQ = "delete from ans_proj where pid = " + currentPid + " and aid = " + id;
            }

            try
            {
                idb.delete(sqlQ);
                JOptionPane.showMessageDialog(this, currentRad + "n har tagits bort.", "Borttagning lyckades", JOptionPane.INFORMATION_MESSAGE);
                setData();
            }

            catch(InfException exception)
            {
                System.out.println("Error: " + exception);
            }
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    
    //Ändrar titeln utifrån om användaren valde partner eller handläggare
    private void setTitle()
    {
        lblTitle.setText("Vänligen välj en " + currentRad.toLowerCase() + " att ta bort");
    }
    
    //Fyller comboboxen utifrån om användaren valde partner eller handläggare
    private void setData()
    {
        String sqlQ = "";
        String sqlQ2 = "";
        ArrayList<String> idLista = new ArrayList<>();
        ArrayList<String> namnLista = new ArrayList<>();
        
        try
        {
            //Om användaren valde partner
            if(currentRad.equals("Partner"))
            {
                sqlQ = "select partner_pid from projekt_partner where pid = " + currentPid;
                idLista = idb.fetchColumn(sqlQ);
                //Lägger in alla relevanta alternativ i comboboxen
                for(String partnerId : idLista)
                {
                    sqlQ = "select namn from partner where pid = " + partnerId;
                    namnLista.add(partnerId + ". " + idb.fetchSingle(sqlQ));
                    Collections.sort(namnLista);
                }
            }
            //Om användaren valde handläggare
            else if(currentRad.equals("Handläggare"))
            {
                sqlQ = "select aid from ans_proj where pid = " + currentPid;
                idLista = idb.fetchColumn(sqlQ);
                //Lägger in alla relevanta alternativ i comboboxen
                for(String handId : idLista)
                {
                    sqlQ = "select fornamn from anstalld where aid = " + handId;
                    sqlQ2 = "select efternamn from anstalld where aid = " + handId;
                    namnLista.add(handId + ". " + idb.fetchSingle(sqlQ) + " " + idb.fetchSingle(sqlQ2));
                    Collections.sort(namnLista);
                }
            }
            
            //Sorterar vår combobox utifrån handläggarnas eller partnernas id
            Collections.sort(namnLista, (a, b) ->  
            {
                int idA = Integer.parseInt(a.substring(0, a.indexOf('.')));
                int idB = Integer.parseInt(b.substring(0, b.indexOf('.')));
                return Integer.compare(idA, idB);
            });
            cboxData.setModel(new javax.swing.DefaultComboBoxModel(namnLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> cboxData;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
