/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.Collections;

/**
 *
 * @author drakm
 */
public class AnsvarigLaggTill extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnsvarigLaggTill.class.getName());
    private InfDB idb;
    private String currentPid;
    private String currentRad;

    /**
     * Creates new form AnsvarigTaBort
     */
    public AnsvarigLaggTill(InfDB idb, String currentPid, String currentRad) {
        this.idb = idb;
        this.currentPid = currentPid;
        this.currentRad = currentRad;
        initComponents();
        setTitle();
        setData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxData = new javax.swing.JComboBox<>();
        btnLaggTill = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboxData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(this::btnLaggTillActionPerformed);

        lblTitle.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cboxData, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnLaggTill)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaggTill))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //När man klickar på "Lägg till"-knappen så läggs partnern eller handläggaren till
    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        String sqlQ = "";
        String id = "";
        
        //Om användaren valde att ta bort en partner
        if(currentRad.equals("Partner"))
        {
            id = cboxData.getSelectedItem().toString();
            id = id.substring(0, id.indexOf('.'));
            sqlQ = "insert into projekt_partner values (" + currentPid + ", " + id + ")";
            System.out.println(sqlQ);
        }
        //Om användaren valde att ta bort en handläggare
        else if(currentRad.equals("Handläggare"))
        {
            id = cboxData.getSelectedItem().toString();
                id = id.substring(0, id.indexOf('.'));
            sqlQ = "insert into ans_proj values (" + currentPid + ", " + id + ")";
        }

        try
        {
            idb.insert(sqlQ);
            JOptionPane.showMessageDialog(this, "Datan har laggts till!", "Tilläg lyckats", JOptionPane.INFORMATION_MESSAGE);
            setData();
        }

        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    
    //Ändrar titeln utifrån om användaren valde partner eller handläggare
    private void setTitle()
    {
        lblTitle.setText("Vänligen välj en " + currentRad.toLowerCase() + " att lägga till i projektet");
    }
    
    //Fyller comboboxen utifrån om användaren valde partner eller handläggare
    private void setData()
    {
        String sqlQ = "";
        String sqlQ2 = "";
        ArrayList<String> idLista = new ArrayList<>();
        ArrayList<String> namnLista = new ArrayList<>();
        
        try
        {
            //Om användaren valde partner
            if(currentRad == "Partner")
            {
                sqlQ = "select pid from partner where pid not in (select partner_pid from projekt_partner where pid = " + currentPid + ")";
                idLista = idb.fetchColumn(sqlQ);
                //Lägger in alla relevanta alternativ i comboboxen
                for(String partnerId : idLista)
                {
                    sqlQ = "select namn from partner where pid = " + partnerId;
                    namnLista.add(partnerId + ". " + idb.fetchSingle(sqlQ));
                }
            }
            //Om användaren valde handläggare
            else if(currentRad == "Handläggare")
            {
                sqlQ = "select aid from anstalld where aid not in (select aid from ans_proj where pid = " + currentPid + ")";
                idLista = idb.fetchColumn(sqlQ);
                //Lägger in alla relevanta alternativ i comboboxen
                for(String handId : idLista)
                {
                    sqlQ = "select fornamn from anstalld where aid = " + handId;
                    sqlQ2 = "select efternamn from anstalld where aid = " + handId;
                    namnLista.add(handId + ". " + idb.fetchSingle(sqlQ) + " " + idb.fetchSingle(sqlQ2));
                }
            }
            
            //Sorterar vår combobox utifrån handläggarnas eller partnernas id
            Collections.sort(namnLista, (a, b) ->  
            {
                int idA = Integer.parseInt(a.substring(0, a.indexOf('.')));
                int idB = Integer.parseInt(b.substring(0, b.indexOf('.')));
                return Integer.compare(idA, idB);
            });
            cboxData.setModel(new javax.swing.DefaultComboBoxModel(namnLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JComboBox<String> cboxData;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
