/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/**
 *
 * @author drakm
 */
public class AvdelningUppgifter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AvdelningUppgifter.class.getName());

    /**
     * Creates new form AvdelningUppgifter
     */
    private InfDB idb;
    private ArrayList<String> avdelningLista;
    private ArrayList<String> uppgiftLista;
    private ArrayList<String> dataLista;
    private String exDataString;
    
    public AvdelningUppgifter(InfDB idb) {
        this.idb = idb;
        exDataString = "";
        ArrayList<String> avdelningLista = new ArrayList<>();
        ArrayList<String> uppgiftLista = new ArrayList<>();
        ArrayList<String> dataLista = new ArrayList<>();
        initComponents();
        setAvdelning();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        cboxAvdelning = new javax.swing.JComboBox<>();
        cboxUppgift = new javax.swing.JComboBox<>();
        cboxAtgard = new javax.swing.JComboBox<>();
        lblAvdelning = new javax.swing.JLabel();
        lblUppgift = new javax.swing.JLabel();
        lblAtgard = new javax.swing.JLabel();
        lblExData = new javax.swing.JLabel();
        lblNyData = new javax.swing.JLabel();
        txtNyData = new javax.swing.JTextField();
        txtExData = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitel.setText("Ändra eller lägg till data om avdelningar");

        cboxAvdelning.addActionListener(this::cboxAvdelningActionPerformed);

        cboxUppgift.addActionListener(this::cboxUppgiftActionPerformed);

        cboxAtgard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ändra", "Lägg till" }));

        lblAvdelning.setText("Avdelning");

        lblUppgift.setText("Uppgift");

        lblAtgard.setText("Åtgärd");

        lblExData.setText("Nuvarande data");

        lblNyData.setText("Ny data");

        txtExData.setEditable(false);

        btnOK.setText("OK");
        btnOK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOKMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAvdelning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboxAvdelning, 0, 398, Short.MAX_VALUE)
                            .addComponent(txtExData))
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUppgift)
                        .addGap(69, 69, 69)
                        .addComponent(lblAtgard)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNyData, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cboxUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboxAtgard, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblExData)
                        .addGap(251, 251, 251)
                        .addComponent(lblNyData)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addGap(280, 280, 280))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitel)
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(lblUppgift)
                    .addComponent(lblAtgard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxAtgard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNyData)
                    .addComponent(lblExData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNyData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnOK)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAvdelningActionPerformed
        String sqlQ = "select column_name from information_schema.columns where table_name = 'avdelning'";
        try
        {
            uppgiftLista = idb.fetchColumn(sqlQ);
            cboxUppgift.setModel(new javax.swing.DefaultComboBoxModel(uppgiftLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }  
    }//GEN-LAST:event_cboxAvdelningActionPerformed

    private void cboxUppgiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxUppgiftActionPerformed
        String sqlQ = "select " + cboxUppgift.getSelectedItem().toString() + " from avdelning where namn = '" + cboxAvdelning.getSelectedItem().toString() + "'";
        
        try
        {
            exDataString = idb.fetchSingle(sqlQ);
            txtExData.setText(exDataString);
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
            
    }//GEN-LAST:event_cboxUppgiftActionPerformed

    private void btnOKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOKMouseClicked
        String sqlQ = "";
        try 
        {
            if(cboxAvdelning.getSelectedItem() == null || cboxUppgift.getSelectedItem() == null || cboxAtgard.getSelectedItem() == null || txtNyData.getText().isEmpty())
            {
                if(cboxAvdelning.getSelectedItem() == null)
                {
                    JOptionPane.showMessageDialog(this, "Vänligen välj en avdelning för att ändra eller lägga till information, tack.", "Ingen avdelning vald", JOptionPane.ERROR_MESSAGE);
                }
                if(cboxUppgift.getSelectedItem() == null)
                {
                    JOptionPane.showMessageDialog(this, "Vänligen välj en uppgift för att ändra eller lägga till information, tack.", "Ingen uppgift vald", JOptionPane.ERROR_MESSAGE);
                }
                if(cboxAtgard.getSelectedItem() == null)
                {
                    JOptionPane.showMessageDialog(this, "Vänligen välj om datan ska ändras eller läggas till, tack.", "Inget åtgärd vald", JOptionPane.ERROR_MESSAGE);
                }
                if(txtNyData.getText().isEmpty())
                {
                    JOptionPane.showMessageDialog(this, "Vänligen skriv in den nya datan för att ändra eller lägga till information, tack.", "Ingen ny datan skriven", JOptionPane.ERROR_MESSAGE);
                }

            }
            else if(cboxAtgard.getSelectedItem().toString() == "Ändra")
            {
                sqlQ = "update avdelning set " + cboxUppgift.getSelectedItem().toString() + " = '" + txtNyData.getText() + "' where namn = '" + txtExData.getText() + "'";
                System.out.println(sqlQ);
                idb.update(sqlQ);
            }
            else if(cboxAtgard.getSelectedItem().toString() == "Lägg till")
            {
                if(txtExData.getText().isEmpty())
                {
                    sqlQ = "insert into avdelning (" + cboxUppgift.getSelectedItem().toString() + ") values ('" + txtNyData.getText() + "')";
                    System.out.println(sqlQ);
                    idb.insert(sqlQ);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Den nuvarande datan måste vara tom för att kunna lägga till ny data. Testa annars \"Ändra\" åtgärdet", "Nuvarande data inte tom", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }//GEN-LAST:event_btnOKMouseClicked

    private void setAvdelning()
    {
        String sqlQ = "select namn from avdelning";
        try
        {
            avdelningLista = idb.fetchColumn(sqlQ);
            cboxAvdelning.setModel(new javax.swing.DefaultComboBoxModel(avdelningLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AvdelningUppgifter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cboxAtgard;
    private javax.swing.JComboBox<String> cboxAvdelning;
    private javax.swing.JComboBox<String> cboxUppgift;
    private javax.swing.JLabel lblAtgard;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblExData;
    private javax.swing.JLabel lblNyData;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblUppgift;
    private javax.swing.JTextField txtExData;
    private javax.swing.JTextField txtNyData;
    // End of variables declaration//GEN-END:variables
}
