/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author drakm
 */
public class AvdelningUppgifter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AvdelningUppgifter.class.getName());

    /**
     * Creates new form AvdelningUppgifter
     */
    private InfDB idb;
    private ArrayList<String> avdelningLista;
    private ArrayList<String> uppgiftLista;
    private ArrayList<String> dataLista;
    
    public AvdelningUppgifter(InfDB idb) {
        this.idb = idb;
        ArrayList<String> avdelningLista = new ArrayList<>();
        ArrayList<String> uppgiftLista = new ArrayList<>();
        ArrayList<String> dataLista = new ArrayList<>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        cboxAvdelning = new javax.swing.JComboBox<>();
        cboxUppgift = new javax.swing.JComboBox<>();
        cboxAtgard = new javax.swing.JComboBox<>();
        lblAvdelning = new javax.swing.JLabel();
        lblUppgift = new javax.swing.JLabel();
        lblAtgard = new javax.swing.JLabel();
        lblExData = new javax.swing.JLabel();
        lblNyData = new javax.swing.JLabel();
        cboxExData = new javax.swing.JComboBox<>();
        txtNyData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitel.setText("Ändra eller lägg till data om avdelningar");

        cboxAvdelning.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboxAvdelningFocusGained(evt);
            }
        });

        cboxUppgift.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboxUppgiftFocusGained(evt);
            }
        });

        cboxAtgard.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ändra", "Lägg till" }));

        lblAvdelning.setText("Avdelning");

        lblUppgift.setText("Uppgift");

        lblAtgard.setText("Åtgärd");

        lblExData.setText("Nuvarande data");

        lblNyData.setText("Ny data");

        cboxExData.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxExData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboxExDataFocusGained(evt);
            }
        });

        txtNyData.addActionListener(this::txtNyDataActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboxAtgard, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(lblAtgard)
                                .addGap(24, 24, 24)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblExData)
                                .addGap(16, 16, 16))
                            .addComponent(cboxExData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblNyData)
                                .addGap(44, 44, 44))
                            .addComponent(txtNyData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxAvdelning, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cboxUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAvdelning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUppgift)
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAtgard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxAtgard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblTitel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAvdelning)
                            .addComponent(lblUppgift))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExData)
                            .addComponent(lblNyData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboxExData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNyData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNyDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNyDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNyDataActionPerformed

    private void cboxAvdelningFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxAvdelningFocusGained
        String sqlQ = "select namn from avdelning";
        try
        {
            avdelningLista = idb.fetchColumn(sqlQ);
            cboxAvdelning.setModel(new javax.swing.DefaultComboBoxModel(avdelningLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }//GEN-LAST:event_cboxAvdelningFocusGained

    private void cboxUppgiftFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxUppgiftFocusGained
        String sqlQ = "select column_name from information_schema.columns where table_name = 'avdelning'";
        try
        {
            uppgiftLista = idb.fetchColumn(sqlQ);
            cboxUppgift.setModel(new javax.swing.DefaultComboBoxModel(uppgiftLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }//GEN-LAST:event_cboxUppgiftFocusGained

    private void cboxExDataFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxExDataFocusGained
        String sqlQ = "select " + cboxUppgift.getSelectedItem().toString() + " from avdelning where namn = '" + cboxAvdelning.getSelectedItem().toString() + "'";
        try
        {
            dataLista = idb.fetchColumn(sqlQ);
            cboxExData.setModel(new javax.swing.DefaultComboBoxModel(dataLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }//GEN-LAST:event_cboxExDataFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AvdelningUppgifter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxAtgard;
    private javax.swing.JComboBox<String> cboxAvdelning;
    private javax.swing.JComboBox<String> cboxExData;
    private javax.swing.JComboBox<String> cboxUppgift;
    private javax.swing.JLabel lblAtgard;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblExData;
    private javax.swing.JLabel lblNyData;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblUppgift;
    private javax.swing.JTextField txtNyData;
    // End of variables declaration//GEN-END:variables
}
