/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.Collections;

/**
 *
 * @author drakm
 */
public class AvdelningUppgifter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AvdelningUppgifter.class.getName());

    /**
     * Creates new form AvdelningUppgifter
     */
    private InfDB idb;
    private String avdid;
    private ArrayList<String> avdidLista;
    private ArrayList<String> avdelningLista;
    private ArrayList<String> uppgiftLista;
    private ArrayList<String> dataLista;
    private String exDataString;
    
    public AvdelningUppgifter(InfDB idb) {
        this.idb = idb;
        exDataString = "";
        avdid = "";
        ArrayList<String> uppgiftLista = new ArrayList<>();
        ArrayList<String> dataLista = new ArrayList<>();
        initComponents();
        setAvdelning();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        cboxAvdelning = new javax.swing.JComboBox<>();
        cboxUppgift = new javax.swing.JComboBox<>();
        lblAvdelning = new javax.swing.JLabel();
        lblUppgift = new javax.swing.JLabel();
        lblExData = new javax.swing.JLabel();
        lblNyData = new javax.swing.JLabel();
        txtNyData = new javax.swing.JTextField();
        txtExData = new javax.swing.JTextField();
        btnUppdatera = new javax.swing.JButton();
        btnLaggTill = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitel.setText("Ändra data om eller lägg till avdelningar");

        cboxAvdelning.addActionListener(this::cboxAvdelningActionPerformed);

        cboxUppgift.addActionListener(this::cboxUppgiftActionPerformed);

        lblAvdelning.setText("Avdelning");

        lblUppgift.setText("Uppgift");

        lblExData.setText("Nuvarande data");

        lblNyData.setText("Ny data");

        txtExData.setEditable(false);

        btnUppdatera.setText("Uppdatera");
        btnUppdatera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUppdateraMouseClicked(evt);
            }
        });

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(this::btnLaggTillActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtExData, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtNyData, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblExData)
                        .addGap(251, 251, 251)
                        .addComponent(lblNyData)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitel)
                        .addGap(216, 216, 216))))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboxAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(lblAvdelning)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cboxUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUppgift)
                        .addGap(127, 127, 127))))
            .addGroup(layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(btnUppdatera)
                .addGap(137, 137, 137)
                .addComponent(btnLaggTill)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvdelning)
                    .addComponent(lblUppgift))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxUppgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNyData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblExData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNyData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUppdatera)
                    .addComponent(btnLaggTill))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //När användaren har valt vilken avdelning som de ska ändra uppgifter för så hämtas alla uppgifter
    private void cboxAvdelningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxAvdelningActionPerformed
        String sqlQ = "select column_name from information_schema.columns where table_name = 'avdelning'";
        try
        {
            uppgiftLista = idb.fetchColumn(sqlQ);
            cboxUppgift.setModel(new javax.swing.DefaultComboBoxModel(uppgiftLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }  
    }//GEN-LAST:event_cboxAvdelningActionPerformed

    //När användaren har valt vilken uppgift de vill ändra data för så hämtas datan för den uppiften som användaren valt för den avdelningen användaren har valt
    private void cboxUppgiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxUppgiftActionPerformed
        getAvdid();
        String sqlQ = "select " + cboxUppgift.getSelectedItem().toString() + " from avdelning where avdid = '" + avdid + "'";
        
        try
        {
            if(idb.fetchSingle(sqlQ) == null)
            {
                txtExData.setText("(INGEN DATA)");
            }
            else
            {
                txtExData.setText(idb.fetchSingle(sqlQ));
            }
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
            
    }//GEN-LAST:event_cboxUppgiftActionPerformed

    //När användaren klickar på "Uppdatera"-knappen så kollar systemet om användaren har valt alla värden som behövs: om användaren har så uppdateras databasen, om inte så får de reda på vad som saknas.
    private void btnUppdateraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUppdateraMouseClicked
        String sqlQ = "";
        String error = "";
        try 
        {
            //Kollar om något saknas från användaren, om det gör så körs koden nedan. Koden nedan är specifikt if-satsen och inte if-else-satser så att användaren får reda på varje fel
            if(cboxAvdelning.getSelectedItem() == null || cboxUppgift.getSelectedItem() == null || txtNyData.getText().isEmpty())
            {
                //Skriver ut om användarne har missat att välja avdelning
                error = Validering.goodStr(cboxAvdelning.getSelectedItem().toString());
                if (error != null) {
                    showError("Gör om gör rätt !! hint: Avdelning: " + error);
                    return;
                }
                
                //Skriver ut om användaren har missat att välja uppgift
                error = Validering.goodStr(cboxUppgift.getSelectedItem().toString());
                if (error != null) {
                    showError("ajdå det verkar vara fel i Uppgift: " + error);
                    return;
                }

                
                //Skriver ut om användaren har missat att skriva vad den gamla datan ska uppdateras till
                error = Validering.goodStr(txtNyData.getText());
                if (error != null) {
                    showError("Oops något gick fel: " + error);
                    return;
                }

            }
            //Om allt stämmer så hämtas den valda avdelningens avdid och vi uppdaterar datan med en sql-query,
            //Efter att tabellen är uppdaterad så uppdaterar avdelning-comboboxen ifall användaren uppdaterade antinge avdid eller namn,
            //Till sist så får användaren en pop-up ruta som informerar användaren om att datan har uppdaterats
            else
            {
                getAvdid();
                sqlQ = "update avdelning set " + cboxUppgift.getSelectedItem().toString() + " = '" + txtNyData.getText() + "' where avdid = " + avdid;
                System.out.println(sqlQ);
                idb.update(sqlQ);
                setAvdelning();
                JOptionPane.showMessageDialog(this, "Datan har uppdaterats till: " + txtNyData.getText(), "Uppdatering lyckades", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }//GEN-LAST:event_btnUppdateraMouseClicked

    //Om användaren klickar på knappen för att lägga till en ny avdelning så får de först en pup-ruta som frågar om de vill lägga till en avdelning (detta är för att det finns inget krav på att man ska kunna ta bort uppgifter),
    //Om användaren klickar "Yes" så läggs det till en ny avdelning med det minsta ike-upptagna avdid och avdelning-comboboxen uppdateras så att man kan ändra uppgifter om den nya avdelningen
    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        //Frågar om konfirmation om användaren vill lägga till en ny avdelning
        if(JOptionPane.showConfirmDialog(this, "Vill du lägga till en ny avdelning?", "Lägg till avdelning?", WIDTH) == 0)
        {
            
            String minstId = "";
            String sqlQ = "select min(avdid) + 1 from avdelning where avdid > 0 and avdid + 1 not in (select avdid from avdelning)";
            try
            {
                minstId = idb.fetchSingle(sqlQ);
                sqlQ = "insert into avdelning (avdid) values (" + minstId + ")";
                idb.insert(sqlQ);
                setAvdelning();
            }
            
            catch(InfException exception)
            {
                System.out.println("Error: " + exception);
            }
        }
 
    }//GEN-LAST:event_btnLaggTillActionPerformed

    //Ger avdelning-comboboxen dess värden (avdid och sedan avdelningens namn) samt sorterar dem.
    //Vi hämtar varje avdelnings avdid och skriver det innan namnet så att vi kan lättare göra sql-querys med avdid senare
    private void setAvdelning()
    {
        String sqlQ = "select avdid from avdelning";
        ArrayList<String> avdidLista = new ArrayList<>();
        ArrayList<String> avdelningLista = new ArrayList<>();
        try
        {
            avdidLista = idb.fetchColumn(sqlQ);
            //Matchar avdelnings namn och avdid och sorterar så att lägst avdid kommer först (att sortera är inte nödvändigt men det ser snyggare ut och blir möjligtvis lättare för användare att använda systemet)
            for(String id : avdidLista)
            {
                sqlQ = "select namn from avdelning where avdid = " + id;
                avdelningLista.add(id + ". " + idb.fetchSingle(sqlQ));
                Collections.sort(avdelningLista);
            }
            cboxAvdelning.setModel(new javax.swing.DefaultComboBoxModel(avdelningLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }
    
    //En get-metod för avdid för den avdelningen som användaren valt i comboboxen
    private void getAvdid()
    {
        String currentAvdelning = cboxAvdelning.getSelectedItem().toString();
        avdid = currentAvdelning.substring(0, currentAvdelning.indexOf('.'));
        
    }
    
    //Visar ett medellande om vad som gick fel om en validering misslyckades
    private void showError(String message) 
    {
        JOptionPane.showMessageDialog(this, message, "Valideringsfel", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new AvdelningUppgifter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnUppdatera;
    private javax.swing.JComboBox<String> cboxAvdelning;
    private javax.swing.JComboBox<String> cboxUppgift;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblExData;
    private javax.swing.JLabel lblNyData;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblUppgift;
    private javax.swing.JTextField txtExData;
    private javax.swing.JTextField txtNyData;
    // End of variables declaration//GEN-END:variables
}
