package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author uuuuhhhhhhhhhhh
 */
public class Hallbarhetsmal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hallbarhetsmal.class.getName());
    
    private InfDB idb;
    /**
     * Creates new form Hallbarhetsmal
     */
    public Hallbarhetsmal(InfDB idb) {
        this.idb = idb;
        hamtaListInfo();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showGoals = new javax.swing.JButton();
        valjMål = new javax.swing.JLabel();
        cboxHallbarhetsMal = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        showGoals.setText("Visa Mål");
        showGoals.addActionListener(this::showGoalsActionPerformed);

        valjMål.setText("jLabel1");

        cboxHallbarhetsMal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxHallbarhetsMal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboxHallbarhetsMalFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showGoals)
                    .addComponent(valjMål)
                    .addComponent(cboxHallbarhetsMal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showGoals)
                .addGap(18, 18, 18)
                .addComponent(valjMål)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxHallbarhetsMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showGoalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGoalsActionPerformed
        try {
            String sqlQ = "select namn from sdgsweden.hallbarhetsmal";
            ArrayList<HashMap<String,String>> databasSvar = idb.fetchRows(sqlQ);
            ArrayList<String> namnlist = new ArrayList<>();
            for (HashMap<String, String> row : databasSvar) {
                namnlist.add(row.get("namn"));
                }
        } catch (InfException ex) {
            System.getLogger(Hallbarhetsmal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
    }//GEN-LAST:event_showGoalsActionPerformed

    private void cboxHallbarhetsMalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxHallbarhetsMalFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxHallbarhetsMalFocusGained
    private void hamtaListInfo() {
        try {
            String sqlQ = "select namn from sdgsweden.hallbarhetsmal";
            ArrayList<HashMap<String,String>> databasSvar = idb.fetchRows(sqlQ);
        } catch (InfException ex) {
            System.getLogger(Hallbarhetsmal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Hallbarhetsmal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxHallbarhetsMal;
    private javax.swing.JButton showGoals;
    private javax.swing.JLabel valjMål;
    // End of variables declaration//GEN-END:variables
}
