package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author uuuuhhhhhhhhhhh
 */
public class Hallbarhetsmal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Hallbarhetsmal.class.getName());
    
    private InfDB idb;
    /**
     * Creates new form Hallbarhetsmal
     */
    public Hallbarhetsmal(InfDB idb) {
        this.idb = idb;
        initComponents();
        hamtaListInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valjMål = new javax.swing.JLabel();
        cboxHallbarhetsMal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfMalBeskrivning = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        valjMål.setText("Hållbarhetsmål");

        cboxHallbarhetsMal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cboxHallbarhetsMal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cboxHallbarhetsMalFocusGained(evt);
            }
        });
        cboxHallbarhetsMal.addActionListener(this::cboxHallbarhetsMalActionPerformed);

        tfMalBeskrivning.setColumns(20);
        tfMalBeskrivning.setLineWrap(true);
        tfMalBeskrivning.setRows(5);
        tfMalBeskrivning.setWrapStyleWord(true);
        jScrollPane1.setViewportView(tfMalBeskrivning);

        jLabel1.setText("Beskrivning:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(valjMål)
                    .addComponent(cboxHallbarhetsMal, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(valjMål)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboxHallbarhetsMal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxHallbarhetsMalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cboxHallbarhetsMalFocusGained
        // TODO Printa ut mål i en 
        
    }//GEN-LAST:event_cboxHallbarhetsMalFocusGained

    private void cboxHallbarhetsMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxHallbarhetsMalActionPerformed
        String FetchDesc = "select beskrivning from hallbarhetsmal where namn = ";
        String valtMal = (String) cboxHallbarhetsMal.getSelectedItem();
        try {
        String UtskriftDesc = idb.fetchSingle(FetchDesc + "'"+valtMal+"'");
        tfMalBeskrivning.setText(UtskriftDesc);
        } catch(InfException ex) {
            System.out.println("Error: " +ex);
        }
    }//GEN-LAST:event_cboxHallbarhetsMalActionPerformed
    private void hamtaListInfo() {
        try {
            String sqlQ = "select namn from sdgsweden.hallbarhetsmal order by hid";
            int i = 1;
            ArrayList<HashMap<String,String>> databasSvar = idb.fetchRows(sqlQ);
            ArrayList<String> namnlist = new ArrayList<>();
            String sqlfraga = "select namn from hallbarhetsmal where hid = ";
            for (HashMap<String, String> row : databasSvar) {
                String malNamn = idb.fetchSingle(sqlfraga + i);
                namnlist.add(row.get("namn"));
                cboxHallbarhetsMal.addItem(malNamn);
                i++;
                }
        } catch (InfException ex) {
            System.getLogger(Hallbarhetsmal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Hallbarhetsmal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxHallbarhetsMal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tfMalBeskrivning;
    private javax.swing.JLabel valjMål;
    // End of variables declaration//GEN-END:variables
}
