package ngo.system;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
/**
 *
 * @author alve
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    
    private InfDB idb;
    //vilken behörighets nivå personen som loggar in har, 0 är vanlig handläggare, 1 är projektchef och 2 är admin
    private int access;

    /**
     * Creates new form Login
     */
    public Login(InfDB idb) {
        this.idb = idb;
        initComponents();
        jLabel1.setVisible(false); devbtnAutoDetail.setVisible(false); // <-- kommentera bort för att få tillbaka dev-knapparna
        lblErr.setVisible(false);
    }
    
    private void showError(String message) {
    JOptionPane.showMessageDialog(this, message, "Valideringsfel", JOptionPane.ERROR_MESSAGE);
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEpost = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        tfEpost = new javax.swing.JTextField();
        lblErr = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        devbtnAutoDetail = new javax.swing.JButton();
        tfPwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblEpost.setText("E-Post");

        lblPwd.setText("Lösenord");

        lblErr.setForeground(new java.awt.Color(255, 0, 0));
        lblErr.setText("Felaktig e-postadress eller lösenord");

        btnLogin.setText("Logga in");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        jLabel1.setText("Utvecklingsverktyg");

        devbtnAutoDetail.setText("Autofyll korrekt login-data");
        devbtnAutoDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                devbtnAutoDetailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblErr)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPwd)
                                .addComponent(lblEpost))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfEpost, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfPwd)))
                        .addComponent(devbtnAutoDetail)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblErr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEpost)
                    .addComponent(tfEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPwd)
                    .addComponent(tfPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(devbtnAutoDetail)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        //Tryck på knappen-logik:
        String epost = tfEpost.getText();
        String pwd = tfPwd.getText();
        String sqlQ = "select losenord from anstalld where epost = '" + epost + "'";
        System.out.println(sqlQ);
        
        //alla sql satser som används för att få reda på någon behörigheter
        String sqlAID = "select anstalld.aid from sdgsweden.anstalld where epost = '" + epost + "'" + " limit 1";
        String sqlIsAdmin = "select anstalld.aid from sdgsweden.anstalld join sdgsweden.admin on sdgsweden.anstalld.aid = sdgsweden.admin.aid where sdgsweden.anstalld.epost = '" + epost + "'" + " limit 1";
        String sqlIsProjektChef = "select anstalld.aid from sdgsweden.anstalld join sdgsweden.projekt on sdgsweden.anstalld.aid = sdgsweden.projekt.projektchef where sdgsweden.anstalld.epost = '" + epost + "'" +  " limit 1";
        String sqlIsHandlaggare = "select anstalld.aid from sdgsweden.anstalld join sdgsweden.handlaggare on sdgsweden.anstalld.aid = sdgsweden.handlaggare.aid where sdgsweden.anstalld.epost = '" + epost + "'" + " limit 1";
        //Först validera epost
        String error = Validering.goodStr(epost);
        if (error != null) {
            showError("E-post: " + error);
            return;
        }
        
        //Validera lösen
        error = Validering.goodStr(pwd);
        if (error != null) {
            showError("Lösenord: " + error);
            return;
        }
        
        try {
            String AID = idb.fetchSingle(sqlAID);
            String isAdmin = idb.fetchSingle(sqlIsAdmin);
            String isProjektchef = idb.fetchSingle(sqlIsProjektChef);
            String isHandlaggare = idb.fetchSingle(sqlIsHandlaggare);
            
        // om någon är handläggare kan den oxå vara projektchef, då finns det en check i if-satsen
        if (AID.equals(isHandlaggare)){
            if (AID.equals(isProjektchef)){
            access = 1;
        }
            else {
            access = 0;
            }
        } 
        
        else if (AID.equals(isAdmin)){
            access = 2;
        }
        
        

        
        System.out.println("nivå=" + access);
            
        } catch (InfException ex) {
            System.getLogger(Login.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        try {
            String dbPwd = idb.fetchSingle(sqlQ);
            if (pwd.equals(dbPwd)) {
                new Meny(idb, epost, access).setVisible(true);
                lblErr.setVisible(false); //ifall vi vill komma åt menyn igen utan ERRMSG
                this.setVisible(false);
            } else {
                lblErr.setVisible(true);
            }
            
        } catch (InfException ex) {
            System.out.println("Error: "+ ex.getMessage());
        }
        
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    private void devbtnAutoDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_devbtnAutoDetailMouseClicked
        tfEpost.setText("maria.g@example.com");
        tfPwd.setText("password123");
    }//GEN-LAST:event_devbtnAutoDetailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton devbtnAutoDetail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblErr;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JTextField tfEpost;
    private javax.swing.JPasswordField tfPwd;
    // End of variables declaration//GEN-END:variables
}
