/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author alve
 */
public class Meny extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Meny.class.getName());
    private InfDB idb; 
    private String activeUser;
    private int permissionLevel;
    private static String currentAID;
    private static InfDB idbStatic;
    private static String staticUser;
    private final int accessLevel;
    
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String activeUser, int accessLevel) {
        this.activeUser = activeUser;
        this.idb = idb;
        this.accessLevel = accessLevel;
        initComponents();
        lblActiveUser.setText(activeUser);
        staticUser = activeUser;
        idbStatic = idb;
        //lblIfAdmin.setText(PLACEHOLDER);
        if (accessLevel == 0){
                lblAccessLevel.setText("handläggare");
                pcKnapp.setVisible(false);
                adminKnapp.setVisible(false);
        }
        if (accessLevel == 1){
                lblAccessLevel.setText("projektchef");
                adminKnapp.setVisible(false);
        }
        if (accessLevel == 2){
                lblAccessLevel.setText("admin");
                pcKnapp.setVisible(false);
        }
        
    }
    
    //En get metod för användarens AID
    public static String getAID(){
        String sqlQ = "select aid from anstalld where epost = ";
        try {
            currentAID = idbStatic.fetchSingle(sqlQ + "'" + staticUser + "'");
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
        
        return currentAID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserPrefix = new javax.swing.JLabel();
        lblActiveUser = new javax.swing.JLabel();
        lblAccessLevel = new javax.swing.JLabel();
        openHallbarhetsMal = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnProjekt = new javax.swing.JButton();
        pcKnapp = new javax.swing.JButton();
        adminKnapp = new javax.swing.JButton();
        btnAvdelningUpggifter = new javax.swing.JButton();
        btnUppgifter = new javax.swing.JButton();
        btnMinaUppgifter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUserPrefix.setText("Inloggad som:");

        lblActiveUser.setText("jLabel1");

        lblAccessLevel.setText("jLabel1");

        openHallbarhetsMal.setText("Hållbarhetsmål");
        openHallbarhetsMal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openHallbarhetsMalMouseClicked(evt);
            }
        });
        openHallbarhetsMal.addActionListener(this::openHallbarhetsMalActionPerformed);

        btnPersonal.setText("Personal");
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalMouseClicked(evt);
            }
        });

        btnProjekt.setText("Projekt");
        btnProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProjektMouseClicked(evt);
            }
        });

        pcKnapp.setText("PC knapp");
        pcKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcKnappMouseClicked(evt);
            }
        });

        adminKnapp.setText("Admin knapp");
        adminKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminKnappMouseClicked(evt);
            }
        });

        btnAvdelningUpggifter.setText("Avdelningsuppgifter");
        btnAvdelningUpggifter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAvdelningUpggifterMouseClicked(evt);
            }
        });
        btnAvdelningUpggifter.addActionListener(this::btnAvdelningUpggifterActionPerformed);

        btnUppgifter.setText("Projekt Uppgifter");
        btnUppgifter.addActionListener(this::btnUppgifterActionPerformed);

        btnMinaUppgifter.setText("Mina Uppgifter");
        btnMinaUppgifter.addActionListener(this::btnMinaUppgifterActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUserPrefix)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblActiveUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(openHallbarhetsMal)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPersonal)
                                    .addComponent(btnProjekt))
                                .addGap(74, 74, 74))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAvdelningUpggifter)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pcKnapp)
                                .addGap(18, 18, 18)
                                .addComponent(adminKnapp)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnMinaUppgifter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserPrefix)
                            .addComponent(lblActiveUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAccessLevel))
                    .addComponent(openHallbarhetsMal))
                .addGap(18, 18, 18)
                .addComponent(btnPersonal)
                .addGap(18, 18, 18)
                .addComponent(btnProjekt)
                .addGap(18, 18, 18)
                .addComponent(btnAvdelningUpggifter)
                .addGap(18, 18, 18)
                .addComponent(btnUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMinaUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcKnapp)
                    .addComponent(adminKnapp))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openHallbarhetsMalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openHallbarhetsMalMouseClicked
        new Hallbarhetsmal(idb).setVisible(true);
    }//GEN-LAST:event_openHallbarhetsMalMouseClicked

    private void btnPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseClicked
        new Personal(idb).setVisible(true); //ersätt null med avdelningen på maria?
    }//GEN-LAST:event_btnPersonalMouseClicked

    private void pcKnappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcKnappMouseClicked
        new ProjektChefGUI(idb, activeUser).setVisible(true);
    }//GEN-LAST:event_pcKnappMouseClicked

    private void adminKnappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminKnappMouseClicked
        new AdminGUI(idb, activeUser).setVisible(true);
    }//GEN-LAST:event_adminKnappMouseClicked

    private void btnAvdelningUpggifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdelningUpggifterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvdelningUpggifterActionPerformed

    private void btnAvdelningUpggifterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvdelningUpggifterMouseClicked
        new AvdelningUppgifter(idb).setVisible(true);
    }//GEN-LAST:event_btnAvdelningUpggifterMouseClicked

    private void openHallbarhetsMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openHallbarhetsMalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openHallbarhetsMalActionPerformed

    private void btnUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppgifterActionPerformed
        new Uppgifter(idb, Meny.getAID()).setVisible(true);
    }//GEN-LAST:event_btnUppgifterActionPerformed

    private void btnMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterActionPerformed
        new MinaUppgifter(idb, Meny.getAID()).setVisible(true);
    }//GEN-LAST:event_btnMinaUppgifterActionPerformed
    
    private void btnProjektMouseClicked(java.awt.event.MouseEvent evt) {                                         
        new Projekt(idb).setVisible(true); 
    }  
    
    
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Meny().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminKnapp;
    private javax.swing.JButton btnAvdelningUpggifter;
    private javax.swing.JButton btnMinaUppgifter;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JButton btnUppgifter;
    private javax.swing.JLabel lblAccessLevel;
    private javax.swing.JLabel lblActiveUser;
    private javax.swing.JLabel lblUserPrefix;
    private javax.swing.JButton openHallbarhetsMal;
    private javax.swing.JButton pcKnapp;
    // End of variables declaration//GEN-END:variables
}
