/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * 
 * @author alve
 */
public class Meny extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Meny.class.getName());
    private InfDB idb; 
    private String activeUser;
    private int permissionLevel;
    private static String currentAID;
    private static InfDB idbStatic;
    private static String staticUser;
    private final int accessLevel;
    
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb, String activeUser, int accessLevel) {
        this.activeUser = activeUser;
        this.idb = idb;
        this.accessLevel = accessLevel;
        initComponents();
        lblActiveUser.setText(activeUser);
        staticUser = activeUser;
        idbStatic = idb;
        //lblIfAdmin.setText(PLACEHOLDER);
        if (accessLevel == 0){
                lblAccessLevel.setText("handläggare");
                pcKnapp.setVisible(false);
                adminKnapp.setVisible(false);
        }
        if (accessLevel == 1){
                lblAccessLevel.setText("projektchef");
                adminKnapp.setVisible(false);
        }
        if (accessLevel == 2){
                lblAccessLevel.setText("admin");
                pcKnapp.setVisible(false);
        }
        
    }
    
    //En get metod för användarens AID
    public static String getAID(){
        String sqlQ = "select aid from anstalld where epost = ";
        try {
            currentAID = idbStatic.fetchSingle(sqlQ + "'" + staticUser + "'");
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
        
        return currentAID;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUserPrefix = new javax.swing.JLabel();
        lblActiveUser = new javax.swing.JLabel();
        lblAccessLevel = new javax.swing.JLabel();
        openHallbarhetsMal = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnProjekt = new javax.swing.JButton();
        pcKnapp = new javax.swing.JButton();
        adminKnapp = new javax.swing.JButton();
        btnAvdelningUpggifter = new javax.swing.JButton();
        btnUppgifter = new javax.swing.JButton();
        btnMinaUppgifter = new javax.swing.JButton();
        btnProjektAnsvar = new javax.swing.JButton();
        btnLandUppgifter = new javax.swing.JButton();
        btnUppgifterOmPartner = new javax.swing.JButton();
        btnPartnersUppgifter = new javax.swing.JButton();
        btnProjektAvd = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUserPrefix.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUserPrefix.setText("Inloggad som:");

        lblActiveUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblActiveUser.setText("jLabel1");

        lblAccessLevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAccessLevel.setText("jLabel1");

        openHallbarhetsMal.setText("Hållbarhetsmål");
        openHallbarhetsMal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openHallbarhetsMalMouseClicked(evt);
            }
        });
        openHallbarhetsMal.addActionListener(this::openHallbarhetsMalActionPerformed);

        btnPersonal.setText("Personal");
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalMouseClicked(evt);
            }
        });

        btnProjekt.setText("Projekt");
        btnProjekt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProjektMouseClicked(evt);
            }
        });
        btnProjekt.addActionListener(this::btnProjektActionPerformed);

        pcKnapp.setText("Projekt-knapp");
        pcKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcKnappMouseClicked(evt);
            }
        });

        adminKnapp.setText("Admin knapp");
        adminKnapp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminKnappMouseClicked(evt);
            }
        });

        btnAvdelningUpggifter.setText("Avdelningsuppgifter");
        btnAvdelningUpggifter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAvdelningUpggifterMouseClicked(evt);
            }
        });
        btnAvdelningUpggifter.addActionListener(this::btnAvdelningUpggifterActionPerformed);

        btnUppgifter.setText("Projekt Uppgifter");
        btnUppgifter.addActionListener(this::btnUppgifterActionPerformed);

        btnMinaUppgifter.setText("Mina Uppgifter");
        btnMinaUppgifter.addActionListener(this::btnMinaUppgifterActionPerformed);

        btnProjektAnsvar.setText("Projekt Ansvar");
        btnProjektAnsvar.addActionListener(this::btnProjektAnsvarActionPerformed);

        btnLandUppgifter.setText("Uppgifter om länder");
        btnLandUppgifter.addActionListener(this::btnLandUppgifterActionPerformed);

        btnUppgifterOmPartner.setText("Uppgifter om partner");
        btnUppgifterOmPartner.addActionListener(this::btnUppgifterOmPartnerActionPerformed);

        btnPartnersUppgifter.setText("Partners Uppgifter");
        btnPartnersUppgifter.addActionListener(this::btnPartnersUppgifterActionPerformed);

        btnProjektAvd.setText("Projekt Sökning");
        btnProjektAvd.addActionListener(this::btnProjektAvdActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblUserPrefix)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblActiveUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(243, 243, 243)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAvdelningUpggifter)
                                    .addComponent(openHallbarhetsMal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPartnersUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMinaUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUppgifterOmPartner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnLandUppgifter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProjektAnsvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProjekt)
                            .addComponent(btnPersonal))
                        .addGap(111, 111, 111))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnProjektAvd)
                    .addComponent(pcKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminKnapp, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserPrefix, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblActiveUser)
                    .addComponent(openHallbarhetsMal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccessLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAvdelningUpggifter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUppgifter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPartnersUppgifter)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMinaUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLandUppgifter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUppgifterOmPartner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProjektAnsvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPersonal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProjekt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProjektAvd)
                .addGap(18, 18, 18)
                .addComponent(adminKnapp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pcKnapp)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openHallbarhetsMalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openHallbarhetsMalMouseClicked
        new Hallbarhetsmal(idb).setVisible(true);
    }//GEN-LAST:event_openHallbarhetsMalMouseClicked

    private void btnPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseClicked
        if(accessLevel == 0 || accessLevel == 1)
        {   
            new Personal(idb).setVisible(true); //ersätt null med avdelningen på maria?
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart handläggare kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPersonalMouseClicked

    private void pcKnappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcKnappMouseClicked
        new ProjektChefGUI(idb, activeUser).setVisible(true);
    }//GEN-LAST:event_pcKnappMouseClicked

    private void adminKnappMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminKnappMouseClicked
        new AdminGUI(idb, activeUser).setVisible(true);
    }//GEN-LAST:event_adminKnappMouseClicked

    private void btnAvdelningUpggifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvdelningUpggifterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvdelningUpggifterActionPerformed

    private void btnAvdelningUpggifterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAvdelningUpggifterMouseClicked
        if(accessLevel == 2)
        {
            new AvdelningUppgifter(idb).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart administratörer kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAvdelningUpggifterMouseClicked

    private void openHallbarhetsMalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openHallbarhetsMalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openHallbarhetsMalActionPerformed

    private void btnUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppgifterActionPerformed
   
        new Uppgifter(idb, Meny.getAID()).setVisible(true);
      
    }//GEN-LAST:event_btnUppgifterActionPerformed

    private void btnMinaUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinaUppgifterActionPerformed
      new MinaUppgifter(idb, Meny.getAID()).setVisible(true);
    }//GEN-LAST:event_btnMinaUppgifterActionPerformed

    private void btnProjektAnsvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektAnsvarActionPerformed
        if(accessLevel == 1)
        {
            new ProjektAnsvar(idb).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart projektledare kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProjektAnsvarActionPerformed

    private void btnLandUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLandUppgifterActionPerformed
        if(accessLevel == 2)
        {
        new LandUppgifter(idb).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart administratörer kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLandUppgifterActionPerformed

    private void btnUppgifterOmPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppgifterOmPartnerActionPerformed
        if(accessLevel == 2)
        {
            new UppgifterOmPartner(idb).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart administratörer kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUppgifterOmPartnerActionPerformed

    private void btnPartnersUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPartnersUppgifterActionPerformed
        if(accessLevel == 0 || accessLevel == 1)
        {
            new PartnersUppgifter(idb).setVisible(true);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart handläggare kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPartnersUppgifterActionPerformed

    private void btnProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektActionPerformed
        
    }//GEN-LAST:event_btnProjektActionPerformed

    private void btnProjektAvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjektAvdActionPerformed
        if(accessLevel == 0 || accessLevel == 1)
        {
            new ProjektAvd(idb).setVisible(true); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart handläggare och projektchefer kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProjektAvdActionPerformed
    

    private void btnProjektMouseClicked1(java.awt.event.MouseEvent evt) {                                         
        
    }  
    
    
    
    

    private void btnProjektMouseClicked(java.awt.event.MouseEvent evt) {
        if(accessLevel == 0 || accessLevel == 1)
        {
            new Projekt(idb, accessLevel).setVisible(true); 
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enbart handläggare och projektchefer kan komma åt den här funktionen.", "Åtkomst nekad", JOptionPane.ERROR_MESSAGE);
        }
    }   

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Meny().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminKnapp;
    private javax.swing.JButton btnAvdelningUpggifter;
    private javax.swing.JButton btnLandUppgifter;
    private javax.swing.JButton btnMinaUppgifter;
    private javax.swing.JButton btnPartnersUppgifter;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnProjekt;
    private javax.swing.JButton btnProjektAnsvar;
    private javax.swing.JToggleButton btnProjektAvd;
    private javax.swing.JButton btnUppgifter;
    private javax.swing.JButton btnUppgifterOmPartner;
    private javax.swing.JLabel lblAccessLevel;
    private javax.swing.JLabel lblActiveUser;
    private javax.swing.JLabel lblUserPrefix;
    private javax.swing.JButton openHallbarhetsMal;
    private javax.swing.JButton pcKnapp;
    // End of variables declaration//GEN-END:variables
}
