/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;


import oru.inf.InfException;
import java.util.ArrayList;
import oru.inf.InfDB;

/**
 *
 * @author user
 */
public class PartnersUppgifter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PartnersUppgifter.class.getName());
    
    private InfDB idb;
    private ArrayList<String> projektNummerLista;
    
    /**
     * Creates new form PartnersUppgifter
     */
    public PartnersUppgifter(InfDB idb) {
        this.idb = idb;
        ArrayList<String> projektNummerLista = new ArrayList<>();
        initComponents();
        setProjekt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxProjekt = new javax.swing.JComboBox<>();
        cboxPartner = new javax.swing.JComboBox<>();
        pnlUppgifter = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboxProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxProjekt.addActionListener(this::cboxProjektActionPerformed);

        cboxPartner.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        pnlUppgifter.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cboxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboxPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxProjektActionPerformed
        getPid();
        setPartner();
    }//GEN-LAST:event_cboxProjektActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    
    private void setProjekt()
    {
        String sqlQ = "select pid from ans_proj where aid = " + Meny.getAID();
        ArrayList<String> projektFullLista = new ArrayList<>();
        try
        {
            projektNummerLista = idb.fetchColumn(sqlQ);
            //Kombinerar alla projekt med deras id och namn så att det blir lättare för sql-queries senare
            for(String projekt : projektNummerLista)
            {
                sqlQ = "select projektnamn from projekt where pid = " + projekt;
                projektFullLista.add(projekt + ". " + idb.fetchSingle(sqlQ));
                
            }
            cboxProjekt.setModel(new javax.swing.DefaultComboBoxModel(projektFullLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }
    
    private void setPartner()
    {
        
    }
    
    private String getPid()
    {
        String pid = cboxProjekt.getSelectedItem().toString();
        pid = pid.substring(0, pid.indexOf('.'));
        return pid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxPartner;
    private javax.swing.JComboBox<String> cboxProjekt;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane pnlUppgifter;
    // End of variables declaration//GEN-END:variables
}
