/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author user
 */
public class PartnersUppgifter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PartnersUppgifter.class.getName());
    
    private InfDB idb;
    private ArrayList<String> projektNummerLista;
    
    /**
     * Creates new form PartnersUppgifter
     */
    public PartnersUppgifter(InfDB idb) {
        this.idb = idb;
        ArrayList<String> projektNummerLista = new ArrayList<>();
        initComponents();
        setProjekt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxProjekt = new javax.swing.JComboBox<>();
        cboxPartner = new javax.swing.JComboBox<>();
        paneUppgifter = new javax.swing.JScrollPane();
        listUppgifter = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cboxProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxProjekt.addActionListener(this::cboxProjektActionPerformed);

        cboxPartner.addActionListener(this::cboxPartnerActionPerformed);

        paneUppgifter.setViewportView(listUppgifter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cboxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxPartner, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(paneUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboxPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(paneUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxProjektActionPerformed
        getPid();
        setPartner();
    }//GEN-LAST:event_cboxProjektActionPerformed

    private void cboxPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPartnerActionPerformed
        setUppgifter();
    }//GEN-LAST:event_cboxPartnerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    
    private void setProjekt()
    {
        String sqlQ = "select pid from ans_proj where aid = " + Meny.getAID();
        ArrayList<String> projektFullLista = new ArrayList<>();
        try
        {
            projektNummerLista = idb.fetchColumn(sqlQ);
            //Kombinerar alla projekt med deras id och namn så att det blir lättare för sql-queries senare
            for(String projekt : projektNummerLista)
            {
                sqlQ = "select projektnamn from projekt where pid = " + projekt;
                projektFullLista.add(projekt + ". " + idb.fetchSingle(sqlQ));
                
            }
            cboxProjekt.setModel(new javax.swing.DefaultComboBoxModel(projektFullLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }
    
    private void setPartner()
    {
        String pid = cboxProjekt.getSelectedItem().toString().substring(0, cboxProjekt.getSelectedItem().toString().indexOf('.'));
        String sqlQ = "select partner_pid from projekt_partner where pid = " + pid;
        ArrayList<String> partnerIdLista = new ArrayList<>();
        ArrayList<String> partnerLista = new ArrayList<>();
        try
        {
            partnerIdLista = idb.fetchColumn(sqlQ);
            //Kombinerar alla partners med deras id och namn så att det blir lättare för sql-queries senare
            for(String id : partnerIdLista)
            {
                sqlQ = "select namn from partner where pid = " + id;
                partnerLista.add(id + ". " + idb.fetchSingle(sqlQ));
                
            }
            cboxPartner.setModel(new javax.swing.DefaultComboBoxModel(partnerLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }
    
    private void setUppgifter()
    {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        String partnerId = cboxPartner.getSelectedItem().toString().substring(0, cboxProjekt.getSelectedItem().toString().indexOf('.'));
        String sqlQ = "select column_name from information_schema.columns where table_name = 'partner'";
        String data = "";
        ArrayList<String> uppgifterLista = new ArrayList<>();
        try
        {
            uppgifterLista = idb.fetchColumn(sqlQ);
            //Lägger in alla uppgifter och datan som hör till dem i en lista
            for(String uppgift : uppgifterLista)
            {
                sqlQ = "select " + uppgift + " from partner where pid = " + partnerId;
                data = idb.fetchSingle(sqlQ);
                uppgift = uppgift.substring(0, 1).toUpperCase() + uppgift.substring(1);
                listModel.addElement(uppgift + ": " + data);
            }
            
            listUppgifter.setModel(listModel);
        }
        
        catch(InfException exception)
        {
                    System.out.println("Error: " + exception);
        }
    }
    
    private String getPid()
    {
        String pid = cboxProjekt.getSelectedItem().toString();
        pid = pid.substring(0, pid.indexOf('.'));
        return pid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboxPartner;
    private javax.swing.JComboBox<String> cboxProjekt;
    private javax.swing.JList<String> listUppgifter;
    private javax.swing.JScrollPane paneUppgifter;
    // End of variables declaration//GEN-END:variables
}
