package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author drakm
 */
public class Personal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Personal.class.getName());
    
    private InfDB idb;
    private String avdelning;
    private String avdelningNummer;
    private String sokning;

    /**
     * Creates new form Personal
     */
    public Personal(InfDB idb) {
        this.idb = idb;
        sokning = "";
        initComponents();
        printAvdelning();
        anstalldLista();
    }
    
    //Kör metoderna setAvdelningNummer och setAvdelning för att få ut vilken avdelning användaren tillhör i form av namnet på avdelning och gör att lblAvdelning visar den avdelningen
    private void printAvdelning()
    {
        setAvdelningNummer();
        setAvdelning();
        lblAvdelning.setText(avdelning);
    }
    
    //Ger fältet avdelningNummer värdet för avdelningen som användaren tillhör med hjälp av AID
    private void setAvdelningNummer()
    {
        try {
            String sqlQ = "select avdelning from anstalld where aid = ";
            avdelningNummer = idb.fetchSingle(sqlQ + Meny.getAID());
        }
        
        catch(InfException exception) {
            System.out.println("Error: " + exception);
        }
    }
    
    //Ger fältet avdelning namnet för avdelningen som användaren tillhör med hjälp av avdid
    private void setAvdelning()
    {
        try {
            String sqlQ = "select namn from avdelning where avdid = ";
            avdelning = idb.fetchSingle(sqlQ + avdelningNummer);
        }
        
        catch(InfException exception) {
            System.out.println("Error: " + exception);
        }
    }
    
    //Hämtar all personal som tillhör samma avdelning som användaren, och skriver antingen ut dem eller alla handlaggare i avdelning som matchar det som användaren har sökt på beroende på om sök-rutan är tom eller inte
    private void anstalldLista()
    {
        try {
            int i = 0;
            String sqlQ;
            DefaultListModel<String> listModel = new DefaultListModel<>();
            ArrayList<HashMap<String, String>> anstalldaNamn;
            ArrayList<String> anstalldaEpost;
            
            //Kollar om sök-rutan är inte tom, om den inte är det så hämtas alla handläggare från avdelningen som matchar det som användaren har skrivit i sök-rutan
            if(!sokning.isEmpty())
            {
                sqlQ = "select fornamn, efternamn from anstalld where avdelning = " + avdelningNummer + " and aid in (select aid from handlaggare)";
                anstalldaNamn = idb.fetchRows(sqlQ);

                sqlQ = "select epost from anstalld where avdelning = " + avdelningNummer + " and aid in (select aid from handlaggare)";
                anstalldaEpost = idb.fetchColumn(sqlQ);
            }
            //Om rutan är tom så hämtar vi all personal på avdelningen
            else {
                sqlQ = "select fornamn, efternamn from anstalld where avdelning = " + avdelningNummer;
                anstalldaNamn = idb.fetchRows(sqlQ);

                sqlQ = "select epost from anstalld where avdelning = " + avdelningNummer;
                anstalldaEpost = idb.fetchColumn(sqlQ);
            }
            
            //Vi skriver ut all personal eller alla handläggare som matchar användarens sökning (beroende på om sökk-rutan är tom eller inte) i model lista
            for (HashMap<String, String> row : anstalldaNamn) {
                String fornamn = row.get("fornamn");
                String efternamn = row.get("efternamn");
                String fullNamn = fornamn + " " + efternamn;
                if(fullNamn.toLowerCase().contains(sokning.toLowerCase()) || anstalldaEpost.get(i).toLowerCase().contains(sokning.toLowerCase()))
                {
                    listModel.addElement(fullNamn);
                }
                i++;
            }
            
            lstAnstallda.setModel(listModel);
        }
        
        catch (InfException exception) {
            System.out.println("Error: " + exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvdelning = new javax.swing.JLabel();
        splAnstallda = new javax.swing.JScrollPane();
        lstAnstallda = new javax.swing.JList<>();
        txtHandlaggare = new javax.swing.JTextField();
        lblHandlaggare = new javax.swing.JLabel();
        btnHandlaggare = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        lblAvdelning.setText("jLabel1");
        lblAvdelning.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lstAnstallda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        splAnstallda.setViewportView(lstAnstallda);

        txtHandlaggare.addActionListener(this::txtHandlaggareActionPerformed);

        lblHandlaggare.setText("Sök efter handläggare i din avdelning utifrån namn eller e-post");

        btnHandlaggare.setText("Sök");
        btnHandlaggare.addActionListener(this::btnHandlaggareActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addComponent(splAnstallda, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lblAvdelning, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHandlaggare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHandlaggare, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnHandlaggare)
                        .addGap(127, 127, 127)))
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblAvdelning)
                .addGap(38, 38, 38)
                .addComponent(splAnstallda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(lblHandlaggare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHandlaggare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHandlaggare)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHandlaggareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHandlaggareActionPerformed
    
    //När knappen klickas så hämtas texten som står i txtHandlaggare och metoden anstalldLista() körs
    private void btnHandlaggareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHandlaggareActionPerformed
        sokning = txtHandlaggare.getText();
        anstalldLista();
    }//GEN-LAST:event_btnHandlaggareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHandlaggare;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblHandlaggare;
    private javax.swing.JList<String> lstAnstallda;
    private javax.swing.JScrollPane splAnstallda;
    private javax.swing.JTextField txtHandlaggare;
    // End of variables declaration//GEN-END:variables
}
