/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import java.util.ArrayList;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.util.Collections;

/**
 *
 * @author drakm
 */
public class ProjektAnsvar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektAnsvar.class.getName());
    
    private InfDB idb;
    private ArrayList<String> projektLista;
    
    /**
     * Creates new form PartnerAnsvarig
     */
    public ProjektAnsvar(InfDB idb) {
        this.idb = idb;
        ArrayList<String> projektLista = new ArrayList<>();
        initComponents();
        setProjekt();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxProjekt = new javax.swing.JComboBox<>();
        btnLaggTill = new javax.swing.JButton();
        btnTaBort = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        cboxRad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboxProjekt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxProjekt.addActionListener(this::cboxProjektActionPerformed);

        btnLaggTill.setText("Lägg till");

        btnTaBort.setText("Ta bort");

        lblTitle.setText("Vänligen välj vilket projekt du vill ta bort eller lägga till en partner eller handläggare ifrån");

        cboxRad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Partner", "Handläggare" }));
        cboxRad.setSelectedItem(-1);
        cboxRad.addActionListener(this::cboxRadActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxRad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnLaggTill)
                        .addGap(24, 24, 24)
                        .addComponent(btnTaBort))
                    .addComponent(lblTitle))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaggTill)
                    .addComponent(btnTaBort)
                    .addComponent(cboxRad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboxProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxProjektActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxProjektActionPerformed

    private void cboxRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxRadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxRadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }
    
    private void setProjekt()
    {
        String sqlQ = "select pid from projekt where projektchef = " + Meny.getAID();
        try
        {
            projektLista = idb.fetchColumn(sqlQ);
            cboxProjekt.setModel(new javax.swing.DefaultComboBoxModel(projektLista.toArray()));
        }
        
        catch(InfException exception)
        {
            System.out.println("Error: " + exception);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> cboxProjekt;
    private javax.swing.JComboBox<String> cboxRad;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
