package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.text.SimpleDateFormat;
import java.util.Date;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author uuuuhhhhhhhhhhh
 */
public class ProjektChefGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProjektChefGUI.class.getName());
    public InfDB idb;
    public String activeUser;
    /**
     * Creates new form ProjektChefGUI
     */
    public ProjektChefGUI(InfDB idb, String activeUser) {
        this.idb = idb;
        this.activeUser = activeUser;
        initComponents();
        hamtaKostnad();
        hamtaLand();
        // hämtar och visar namn på personen som loggar in
        String sqlForNamn = "select fornamn from sdgsweden.anstalld where epost = '" + activeUser + "'";
        String sqlEfterNamn = "select efternamn from sdgsweden.anstalld where epost = '" + activeUser + "'";
        try {
            String fNamn = idb.fetchSingle(sqlForNamn);
            String eNamn = idb.fetchSingle(sqlEfterNamn);
            jLabelName.setText("Välkommen " + fNamn + " " + eNamn + "");
        } catch (InfException ex) {
            System.getLogger(ProjektChefGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    private ProjektChefGUI() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void showError(String message) {
    JOptionPane.showMessageDialog(this, message, "Valideringsfel", JOptionPane.ERROR_MESSAGE);
}
      
    private void hamtaKostnad(){
        try {
            //hämtar aid för personen som loggat in
            String sqlAID = "select aid from sdgsweden.anstalld where epost = '" + activeUser + "'";
            String aid = idb.fetchSingle(sqlAID);
            //hämtar projektnamn och placerar in det i en combobox
            String sqlQ = "select projektnamn from sdgsweden.projekt order by projektnamn";
            int i = 1;
            ArrayList<HashMap<String,String>> databasSvar = idb.fetchRows(sqlQ);
            ArrayList<String> projektLista = new ArrayList<>();
            String sqlfraga = "select projektnamn from sdgsweden.projekt where pid = ";
            for (HashMap<String, String> row : databasSvar){
            String projektNamn = idb.fetchSingle(sqlfraga + i + " and projektchef = " + aid);
            projektLista.add(row.get("projektnamn"));
            if (projektNamn != null){
                projektBox.addItem(projektNamn);
            }
            i++; 
            }
            
        } catch (InfException ex) {
            System.getLogger(ProjektChefGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
           

    }
    
    private void hamtaLand(){
    try {
            String sqlQ = "select namn from land order by lid";
            int i = 1;
            ArrayList<HashMap<String,String>> databasSvar = idb.fetchRows(sqlQ);
            ArrayList<String> landLista = new ArrayList<>();
            String sqlfraga = "select namn from land where lid = ";
            for (HashMap<String, String> row : databasSvar){
                String landNamn = idb.fetchSingle(sqlfraga + i);
                landLista.add(row.get("projektnamn"));
                if (landNamn != null){
                    landKostnadBox.addItem(landNamn);
                } 
                i++;
            }
        } catch (InfException ex) {
            System.getLogger(ProjektChefGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    private boolean validDate(String slutDatum){
         return slutDatum.matches("\\d{4}-\\d{2}-\\d{2}");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        PCLabel = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        projektBox = new javax.swing.JComboBox<>();
        kostnadLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tfLandInfo = new javax.swing.JTextArea();
        landKostnadBox = new javax.swing.JComboBox<>();
        landKostnadLabel = new javax.swing.JLabel();
        textFieldBeskrivning = new javax.swing.JTextField();
        textFieldKostnad = new javax.swing.JTextField();
        textFieldPrioritet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnUppdatera = new javax.swing.JButton();
        textFieldNamn = new javax.swing.JTextField();
        textFieldStatus = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldSlutDatum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        textFieldStartDatum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PCLabel.setText("Projekt Chef Meny");

        jLabelName.setText("Välkommen ");

        projektBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        projektBox.addActionListener(this::projektBoxActionPerformed);

        kostnadLabel.setText("jLabel1");

        tfLandInfo.setEditable(false);
        tfLandInfo.setColumns(20);
        tfLandInfo.setLineWrap(true);
        tfLandInfo.setRows(5);
        tfLandInfo.setWrapStyleWord(true);
        jScrollPane2.setViewportView(tfLandInfo);

        landKostnadBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        landKostnadBox.addActionListener(this::landKostnadBoxActionPerformed);

        landKostnadLabel.setText("jLabel1");

        jLabel1.setText("Projektnamn");

        jLabel2.setText("Beskrivning");

        jLabel3.setText("Slutdatum");

        jLabel4.setText("Kostnad");

        jLabel5.setText("Prioritet");

        btnUppdatera.setText("Uppdatera");
        btnUppdatera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUppdateraMouseClicked(evt);
            }
        });

        jLabel6.setText("Status");

        textFieldSlutDatum.setText("(yyyy-mm-dd)");

        jLabel7.setText("Kostnad:");

        textFieldStartDatum.setText("(yyyy-mm-dd)");

        jLabel8.setText("Startdatum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PCLabel)
                    .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(landKostnadLabel)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kostnadLabel)
                                .addGap(162, 162, 162)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(textFieldNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel8))
                                    .addComponent(textFieldStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel3))
                                    .addComponent(textFieldSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(textFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnUppdatera))))
                    .addComponent(projektBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(landKostnadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PCLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projektBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kostnadLabel)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landKostnadBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landKostnadLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldSlutDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textFieldKostnad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldPrioritet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textFieldStartDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldBeskrivning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textFieldNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUppdatera)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projektBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projektBoxActionPerformed
        //hämtar kostnad för projektet och placerar det nummret i en jLabel
        String fetchKostnad = "select kostnad from projekt where projektnamn = ";
        String valtProjekt = (String) projektBox.getSelectedItem();
        try {
            String utskriftKostnad = idb.fetchSingle(fetchKostnad + "'" + valtProjekt + "'");
            kostnadLabel.setText(utskriftKostnad + " kr");
        }
        catch(InfException ex) {
            System.out.println("Error: " +ex);
        }
        
        //hämtar land ID för att identifiera landet
        String fetchLandID = "select land from projekt where projektnamn = ";
        try {
            //hämtar land info och placerar informationen i ett textfält
            //
            String lid = idb.fetchSingle(fetchLandID + "'" + valtProjekt + "'");
            //hämtar landnamn, landspråk, osv, för landet och placerar i textfält. alla gör samma sak bara för olika kolumner
            String fetchLand = "select namn from land where lid = ";
            String landNamn = idb.fetchSingle(fetchLand + lid);
            
            String fetchLandSprak = "select sprak from land where lid = ";
            String landSprak = idb.fetchSingle(fetchLandSprak + lid);
            
            String fetchLandValuta = "select valuta from land where lid = ";
            String landValuta = idb.fetchSingle(fetchLandValuta + lid);
            
            String fetchLandTidszon = "select tidszon from land where lid = ";
            String landTidszon = idb.fetchSingle(fetchLandTidszon + lid);
            
            String fetchLandPolitik = "select politisk_struktur from land where lid = ";
            String landPolitik = idb.fetchSingle(fetchLandPolitik + lid);
            
            String fetchLandEkomoni = "select ekonomi from land where lid = ";
            String landEkomoni = idb.fetchSingle(fetchLandEkomoni + lid);
            
            //sätter in informationen i textfältet
            String landInfo = (landNamn + ", " + landSprak + ", " + landValuta + ", " + landTidszon + ", " + landPolitik + ", " + landEkomoni);
            tfLandInfo.setText(landInfo);
            
            
            
            
               
        } catch (InfException ex) {
            System.getLogger(ProjektChefGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_projektBoxActionPerformed

    private void landKostnadBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landKostnadBoxActionPerformed
        
        try {
            String valtLand = (String) landKostnadBox.getSelectedItem();
            String fetchLandID = "SELECT lid FROM land WHERE namn = '" + valtLand + "'";
            String landID = idb.fetchSingle(fetchLandID);
            String fetchKostnad = "SELECT projektnamn, kostnad FROM projekt WHERE land = " + landID;
            
            StringBuilder kostnadUppDelning = new StringBuilder();
            ArrayList<HashMap<String, String>> databasSvar = idb.fetchRows(fetchKostnad);
            for (HashMap<String, String> row : databasSvar) {
            String projektnamn = row.get("projektnamn");
            String kostnad = row.get("kostnad");
            kostnadUppDelning.append(projektnamn).append(", ").append(kostnad).append(" kr || ");
            }

        landKostnadLabel.setText(kostnadUppDelning.toString());

        } catch (InfException ex) {
            System.getLogger(ProjektChefGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
        //String sqlQ = "select namn from land order by lid";
        //    int i = 1;
        //    ArrayList<HashMap<String,String>> databasSvar = idb.fetchRows(sqlQ);
        //    ArrayList<String> landLista = new ArrayList<>();
        //    String sqlfraga = "select namn from land where lid = ";
        //    for (HashMap<String, String> row : databasSvar){
        //        String landNamn = idb.fetchSingle(sqlfraga + i);
        //        landLista.add(row.get("projektnamn"));
        //        if (landNamn != null){
        //            landKostnadBox.addItem(landNamn);
        //        } 
        //        i++;
        
        
    }//GEN-LAST:event_landKostnadBoxActionPerformed

    private void btnUppdateraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUppdateraMouseClicked
        
        //väljer vilket projekt man vill ändra uppgifter hos
        String valtProjekt = (String) projektBox.getSelectedItem();
        try {

            String errorNamn = Validering.goodStr(textFieldNamn.getText());
            if (errorNamn != null) {
            showError("Projektnamn: " + errorNamn);
            return;
        }
        
        else {
            //update-satsen för att ändra i databasen
            String sqlNamn = "update projekt set projektnamn = '" + textFieldNamn.getText() + "' where projektnamn = '" + valtProjekt + "'";
            idb.update(sqlNamn);
            //ändrar "valtProjekt" så att satserna nedan inte använder gamla projektnamnet som "where"-värde
            valtProjekt = textFieldNamn.getText();  
        }
        
            String errorBeskrivning = Validering.goodStr(textFieldBeskrivning.getText());
            if (errorBeskrivning != null) {
            showError("Beskrivning: " + errorBeskrivning);
            return;
        }
        
        else {
            String sqlBeskrivning = "update projekt set beskrivning = '" + textFieldBeskrivning.getText() + "' where projektnamn = '" + valtProjekt + "'";
            idb.update(sqlBeskrivning);
        }
            
            
        String errorStartDatum = Validering.goodStr(textFieldStartDatum.getText());
            if (errorStartDatum != null) {
            showError("Start datum: " + errorStartDatum);
            return;
        }
        
        errorStartDatum = Validering.datumValid(textFieldStartDatum.getText());
            if(errorStartDatum != null) {
            showError("Startdatum: " + errorStartDatum);
            return;
        }
            
        else {
            String sqlStartDatum = "update projekt set startdatum = '" + textFieldSlutDatum.getText() + "' where projektnamn = '" + valtProjekt + "'";
            idb.update(sqlStartDatum);
        }
        
        
        
        String errorSlutDatum = Validering.goodStr(textFieldSlutDatum.getText());
            if (errorSlutDatum != null) {
            showError("Slut datum: " + errorSlutDatum);
            return;
            }
        
        errorSlutDatum = Validering.datumValid(textFieldSlutDatum.getText());
            if(errorSlutDatum != null) {
            showError("Slutdatum: " + errorSlutDatum);
            return;
            }
            
        else {
            String sqlSlutDatum = "update projekt set slutdatum = '" + textFieldSlutDatum.getText() + "' where projektnamn = '" + valtProjekt + "'";
            idb.update(sqlSlutDatum);
        }
        
        //hämter string värdet för textFieldKostnad och omvandlar den till en double, som sen kan checkas med "Validering.goodInt"
        String kostnadString = textFieldKostnad.getText();

        if (kostnadString.isEmpty()) {
            showError("Kostnad: Inputsträng tom!");
            return;
        }

        double kostnad;
        try {
            kostnad = Double.parseDouble(kostnadString);
        } catch (NumberFormatException e) {
            showError("Kostnad: Ogiltig inmatning!");
            return;
        }

        String errorKostnad = Validering.goodDbl(kostnad);
        if (errorKostnad != null) {
            showError("Kostnad: " + errorKostnad);
            return;
        }
        
        else {
            String sqlKostnad = "update projekt set kostnad = '" + textFieldKostnad.getText() + "' where projektnamn = '" + valtProjekt + "'";
            idb.update(sqlKostnad);
        }
        
        String errorStatus = Validering.goodStr(textFieldStatus.getText());
            if (errorStatus != null) {
            showError("Status: " + errorStatus);
            return;
        }
        
        else {
            String sqlStatus = "update projekt set status = '" + textFieldStatus.getText() + "' where projektnamn = '" + valtProjekt + "'";
            idb.update(sqlStatus);
        }
        
        String errorPriotitet = Validering.goodStr(textFieldPrioritet.getText());
            if (errorPriotitet != null) {
            showError("Priotitet: " + errorPriotitet);
            return;
        }
        
        else {
            String sqlPrioritet = "update projekt set prioritet = '" + textFieldPrioritet.getText() + "' where projektnamn = '" + valtProjekt + "'";
            idb.update(sqlPrioritet);
        }

        } catch (InfException ex) {
                System.getLogger(ProjektChefGUI.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        
        
        
    }//GEN-LAST:event_btnUppdateraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ProjektChefGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PCLabel;
    private javax.swing.JButton btnUppdatera;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel kostnadLabel;
    private javax.swing.JComboBox<String> landKostnadBox;
    private javax.swing.JLabel landKostnadLabel;
    private javax.swing.JComboBox<String> projektBox;
    private javax.swing.JTextField textFieldBeskrivning;
    private javax.swing.JTextField textFieldKostnad;
    private javax.swing.JTextField textFieldNamn;
    private javax.swing.JTextField textFieldPrioritet;
    private javax.swing.JTextField textFieldSlutDatum;
    private javax.swing.JTextField textFieldStartDatum;
    private javax.swing.JTextField textFieldStatus;
    private javax.swing.JTextArea tfLandInfo;
    // End of variables declaration//GEN-END:variables

    
}
