/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo.system;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author drakm
 */
public class Projekt extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Projekt.class.getName());
    private InfDB idb;
    private String avdelning;
    private String avdelningNummer;
    private String startDatumString;
    private String slutDatumString;
    private String epost;
    private LocalDate startDatum;
    private LocalDate slutDatum;
    private ArrayList<String> projektNamn;
    private String epostChef;

    /**
     * Creates new form Projekt
     */
    public Projekt(InfDB idb) {
        this.idb = idb;
        startDatumString = "";
        slutDatumString = "";
        epost = "";
        ArrayList<String> projektNamn = new ArrayList<>();
        epostChef = "";
        initComponents();
        printAvdelning();
        projektLista();
    }
    
    //Ändrar lblAvdelning till att visa avdelningens namn som användaren jobbar på
    private void printAvdelning()
    {
        setAvdelningNummer();
        setAvdelning();
        lblAvdelning.setText(avdelning);
    }
    
    //Ger fältet avdelningNummer värdet för avdelningen som användaren tillhör med hjälp av AID
    private void setAvdelningNummer()
    {
        try {
            String sqlQ = "select avdelning from anstalld where aid = ";
            avdelningNummer = idb.fetchSingle(sqlQ + Meny.getAID());
        }
        
        catch(InfException exception) {
            System.out.println("Error: " + exception);
        }
    }
    
    //Ger fältet avdelning namnet för avdelningen som användaren tillhör med hjälp av avdid
    private void setAvdelning()
    {
        try {
            String sqlQ = "select namn from avdelning where avdid = ";
            avdelning = idb.fetchSingle(sqlQ + avdelningNummer);
        }
        
        catch(InfException exception) {
            System.out.println("Error: " + exception);
        }
    }
    
    //Skapar en lista för alla projekt som finns i avdelningen som användaren jobbar på och som är aktiva samt ingår i det datumet användaren skrivit in om de har det
    private void projektLista()
    {
        try {
            String sqlQ;
            DefaultListModel<String> listModel = new DefaultListModel<>();

            //Kollar om användaren har sökt på ett specifikt datum, om de inte har så körs kod-blocket nedan
            if(startDatumString.isEmpty() || slutDatumString.isEmpty())
            {
                sqlQ = "select projektnamn from projekt where status = 'Pågående' and pid in (select pid from ans_proj where aid in (select aid from anstalld where avdelning = " + avdelningNummer + "))";
            }
            //Om de har sökt på ett datum så körs kod-blocket nedan
            else
            {
                sqlQ = "select projektnamn from projekt where status = 'Pågående' and startdatum >= '" + startDatum + "' and slutdatum <= '" + slutDatum + "' and pid in (select pid from ans_proj where aid in (select aid from anstalld where avdelning = " + avdelningNummer + "))";
            }
            
            projektNamn = idb.fetchColumn(sqlQ);
            
            for (int i = 0; i < projektNamn.size(); i++) {
                String currentProjektNamn = projektNamn.get(i);
                sqlQ = "select epost from anstalld where aid in (select projektchef from projekt where projektnamn = '" + projektNamn.get(i) + "')";
                epostChef = idb.fetchSingle(sqlQ);
                if(epostChef.toLowerCase().contains(epost.toLowerCase()))
                {
                    listModel.addElement(currentProjektNamn);
                }
            }
            
            lstProjekt.setModel(listModel);
        }
        
        catch (InfException exception) {
            System.out.println("Error: " + exception);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvdelning = new javax.swing.JLabel();
        splProjekt = new javax.swing.JScrollPane();
        lstProjekt = new javax.swing.JList<>();
        txtStart = new javax.swing.JTextField();
        txtSlut = new javax.swing.JTextField();
        btnDatum = new javax.swing.JButton();
        lblStart = new javax.swing.JLabel();
        lblSlut = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEpost = new javax.swing.JTextField();
        lblEpost = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblAvdelning.setText("jLabel1");

        lstProjekt.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        splProjekt.setViewportView(lstProjekt);

        btnDatum.setText("Sök");
        btnDatum.addActionListener(this::btnDatumActionPerformed);

        lblStart.setText("Startdatum");

        lblSlut.setText("Slutdatum");

        lblFormat.setText("(YYYY-MM-DD)");

        jLabel1.setText("Sök inom ett datum eller på en användares E-post");

        txtEpost.addActionListener(this::txtEpostActionPerformed);

        lblEpost.setText("E-post");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(splProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEpost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(103, 103, 103)
                                            .addComponent(lblEpost)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(83, 83, 83)
                                            .addComponent(txtSlut, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblStart)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblFormat)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblSlut)
                                            .addGap(13, 13, 13))))))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDatum)
                        .addGap(164, 164, 164))))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblAvdelning)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblAvdelning)
                .addGap(18, 18, 18)
                .addComponent(splProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStart)
                    .addComponent(lblSlut)
                    .addComponent(lblFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSlut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblEpost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDatum)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Om användaren klickar på sök-knappen så hämtar vi värdena som står i datum-rutorna och gör om em från Strings till LocalDate samt kör projektLista() metoden för att uppdatera projekt-listan
    private void btnDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatumActionPerformed
        startDatumString = txtStart.getText();
        slutDatumString = txtSlut.getText();
        epost = txtEpost.getText();
         
        if((!startDatumString.isEmpty() || !slutDatumString.isEmpty()) && (startDatumString.length() != 10 || slutDatumString.length() != 10))
        {
            JOptionPane.showMessageDialog(null, "Vänligen skriv in start- och slutdatum i formatet YYYY-MM-DD (bindestreck inkluderat) för att söka på aktiva projekt inom de datumen.", "Tom sökning", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            if(!startDatumString.isEmpty() || !slutDatumString.isEmpty())
            {
                DateTimeFormatter format = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                startDatum = LocalDate.parse(startDatumString, format);
                slutDatum = LocalDate.parse(slutDatumString, format); 
            }
            projektLista();
        }
    }//GEN-LAST:event_btnDatumActionPerformed

    private void txtEpostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEpostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEpostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Projekt().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvdelning;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblSlut;
    private javax.swing.JLabel lblStart;
    private javax.swing.JList<String> lstProjekt;
    private javax.swing.JScrollPane splProjekt;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtSlut;
    private javax.swing.JTextField txtStart;
    // End of variables declaration//GEN-END:variables
}
